listDairy = ["Dairy",
             "white eggs L",
             "delicious milk",
             "nature megumi",
             "Hokkaido pure fresh cream 35",
             "Hokkaido sour cream",
             "organic soy milk, unsweetened",
             "almond effect",
             "Tropicana Whole Fruit 100% Orange",
             "Hokkaido butter",
             "Hotel margarine", "Cream cheese"]

listFish = ["Fish",
            "sashimi trout",
            "fish fillet mackerel",
            "white shrimp",
            "squid fillet cut",
            "seafood mix",
            "shelled clams ",
            "salted sockeye salmon",
            "red fish pickled in sake lees",
            "boiled whitebait",
            "tarako",
            "shiokara",
            "wakame seaweed from Naruto waters",
            "fatty mackerel teriyaki",
            "fragrant genuine wasabi"]

listMeat = ["Meat",
            "chicken",
            "pork",
            "beef"]

listFruits = ["Fruits",
              "banana",
              "muscat",
              "kiwi",
              "gold kiwi",
              "persimmon",
              "avocado",
              "orange"]

listVegetables = ["Vegetables",
                  "onion",
                  "carrot",
                  "cherry tomato",
                  "green onion",
                  "cucumber",
                  "potato",
                  "broccoli",
                  "eggplant",
                  "lettuce",
                  "cabbage",
                  "green pepper",
                  "shimeji mushroom",
                  "enoki mushroom",
                  "japanese mustard spinach",
                  "half white radish",
                  "chinese cabbage"]

listCategory = [listDairy, listFish, listMeat, listFruits, listVegetables]